# Goal: Load cleaned_activity_data.csv into MySQL (behaviorpulse.activities)
Status: DONE ✅
Rows: 120

In [1]:
import pandas as pd
print("pandas ok")

pandas ok

In [2]:
df = pd.read_csv(r"C:\temp\cleaned_activity_data.csv")
df.shape, df.columns.tolist()

((120, 18),
 ['record_id',
  'user_id',
  'date',
  'day_of_week',
  'activity_type',
  'planned_time_hrs',
  'actual_time_hrs',
  'completion_status',
  'interruption_count',
  'energy_level',
  'mood',
  'remarks',
  'invalid_time_flag',
  'energy_missing_flag',
  'duplicate_flag',
  'efficiency',
  'burnout_risk',
  'high_interruption_flag'])

In [3]:
# 1. Drop extra column
df = df.drop(columns=['remarks'])

# 2. Rename date column to match table
df = df.rename(columns={'date': 'activity_date'})

# 3. Ensure correct column order (CRITICAL)
df = df[
    [
        'record_id',
        'user_id',
        'activity_date',
        'day_of_week',
        'activity_type',
        'planned_time_hrs',
        'actual_time_hrs',
        'completion_status',
        'interruption_count',
        'energy_level',
        'mood',
        'invalid_time_flag',
        'energy_missing_flag',
        'duplicate_flag',
        'efficiency',
        'burnout_risk',
        'high_interruption_flag'
    ]
]

# 4. Convert NaN → None for MySQL
df = df.where(pd.notnull(df), None)

In [6]:
df.shape
df.columns.tolist()

['record_id',
 'user_id',
 'activity_date',
 'day_of_week',
 'activity_type',
 'planned_time_hrs',
 'actual_time_hrs',
 'completion_status',
 'interruption_count',
 'energy_level',
 'mood',
 'invalid_time_flag',
 'energy_missing_flag',
 'duplicate_flag',
 'efficiency',
 'burnout_risk',
 'high_interruption_flag']

In [8]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Acs1112@mysql",
    database="behaviorpulse"
)

cursor = conn.cursor()

In [10]:
# make all column names lowercase
df.columns = df.columns.str.lower()

In [11]:
df.columns.tolist()

['record_id',
 'user_id',
 'activity_date',
 'day_of_week',
 'activity_type',
 'planned_time_hrs',
 'actual_time_hrs',
 'completion_status',
 'interruption_count',
 'energy_level',
 'mood',
 'invalid_time_flag',
 'energy_missing_flag',
 'duplicate_flag',
 'efficiency',
 'burnout_risk',
 'high_interruption_flag']

In [12]:
# drop extra column if still present
if 'remarks' in df.columns:
    df = df.drop(columns=['remarks'])

# rename date column
df = df.rename(columns={'date': 'activity_date'})

# enforce correct order
df = df[
    [
        'record_id',
        'user_id',
        'activity_date',
        'day_of_week',
        'activity_type',
        'planned_time_hrs',
        'actual_time_hrs',
        'completion_status',
        'interruption_count',
        'energy_level',
        'mood',
        'invalid_time_flag',
        'energy_missing_flag',
        'duplicate_flag',
        'efficiency',
        'burnout_risk',
        'high_interruption_flag'
    ]
]

# NaN → None
df = df.where(pd.notnull(df), None)

In [13]:
df.shape
df.columns.tolist()

['record_id',
 'user_id',
 'activity_date',
 'day_of_week',
 'activity_type',
 'planned_time_hrs',
 'actual_time_hrs',
 'completion_status',
 'interruption_count',
 'energy_level',
 'mood',
 'invalid_time_flag',
 'energy_missing_flag',
 'duplicate_flag',
 'efficiency',
 'burnout_risk',
 'high_interruption_flag']

In [15]:
# find any literal 'nan' strings
(df == 'nan').sum()

record_id                 0
user_id                   0
activity_date             0
day_of_week               0
activity_type             0
planned_time_hrs          0
actual_time_hrs           0
completion_status         0
interruption_count        0
energy_level              0
mood                      0
invalid_time_flag         0
energy_missing_flag       0
duplicate_flag            0
efficiency                0
burnout_risk              0
high_interruption_flag    0
dtype: int64

In [21]:
# rename date column to match table
df = df.rename(columns={"date": "activity_date"})

In [22]:
import numpy as np
df = df.where(pd.notnull(df), None)

In [23]:
cols = [
    "record_id", "user_id", "activity_date", "day_of_week", "activity_type",
    "planned_time_hrs", "actual_time_hrs", "completion_status",
    "interruption_count", "energy_level", "mood",
    "invalid_time_flag", "energy_missing_flag", "duplicate_flag",
    "efficiency", "burnout_risk", "high_interruption_flag"
]

df = df[cols]

In [24]:
df.head()

,record_id,user_id,activity_date,day_of_week,activity_type,planned_time_hrs,actual_time_hrs,completion_status,interruption_count,energy_level,mood,invalid_time_flag,energy_missing_flag,duplicate_flag,efficiency,burnout_risk,high_interruption_flag
0,1,101,2025-11-01,mon,study,3.0,2.5,yes,2,4.0,high,False,False,False,0.833333,0,False
1,2,101,2025-11-02,tue,study,2.0,3.0,yes,5,3.0,neutral,False,False,False,1.500000,0,True
2,3,101,2025-11-03,wed,study,3.0,1.5,no,7,3.0,low,False,True,False,0.500000,0,True
3,4,101,2025-11-04,thu,work,4.0,4.5,yes,1,5.0,high,False,False,False,1.125000,0,False
4,5,101,2025-11-05,fri,rest,1.0,0.5,no,3,2.0,low,False,False,False,0.500000,0,False

In [25]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Acs1112@mysql",   # your actual password
    database="behaviorpulse"
)

cursor = conn.cursor()

In [28]:
import numpy as np

df = df.replace({np.nan: None})

In [29]:
df.isnull().sum()

record_id                 0
user_id                   0
activity_date             0
day_of_week               0
activity_type             0
planned_time_hrs          0
actual_time_hrs           5
completion_status         0
interruption_count        0
energy_level              0
mood                      0
invalid_time_flag         0
energy_missing_flag       0
duplicate_flag            0
efficiency                5
burnout_risk              0
high_interruption_flag    0
dtype: int64

In [30]:
insert_query = """
INSERT INTO activities (
    record_id, user_id, activity_date, day_of_week, activity_type,
    planned_time_hrs, actual_time_hrs, completion_status,
    interruption_count, energy_level, mood,
    invalid_time_flag, energy_missing_flag, duplicate_flag,
    efficiency, burnout_risk, high_interruption_flag
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [31]:
cursor.executemany(insert_query, df.values.tolist())
conn.commit()

print("Rows inserted:", cursor.rowcount)

Rows inserted: 120

In [33]:
df_check = pd.read_sql("SELECT * FROM activities LIMIT 5", conn)
df_check

C:\Users\chira\AppData\Local\Temp\ipykernel_7152\2490816803.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_check = pd.read_sql("SELECT * FROM activities LIMIT 5", conn)

,record_id,user_id,activity_date,day_of_week,activity_type,planned_time_hrs,actual_time_hrs,completion_status,interruption_count,energy_level,mood,invalid_time_flag,energy_missing_flag,duplicate_flag,efficiency,burnout_risk,high_interruption_flag
0,1,101,2025-11-01,mon,study,3.0,2.5,yes,2,4,high,0,0,0,0.833333,0,0
1,2,101,2025-11-02,tue,study,2.0,3.0,yes,5,3,neutral,0,0,0,1.500000,0,1
2,3,101,2025-11-03,wed,study,3.0,1.5,no,7,3,low,0,1,0,0.500000,0,1
3,4,101,2025-11-04,thu,work,4.0,4.5,yes,1,5,high,0,0,0,1.125000,0,0
4,5,101,2025-11-05,fri,rest,1.0,0.5,no,3,2,low,0,0,0,0.500000,0,0

# ANALYSIS

In [34]:
pd.read_sql("""
SELECT activity_type, AVG(efficiency) AS avg_eff
FROM activities
GROUP BY activity_type
""", conn)

C:\Users\chira\AppData\Local\Temp\ipykernel_7152\1512095930.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("""

  activity_type   avg_eff
0         study  0.921802
1          work  0.961000
2          rest  0.934211

In [35]:
pd.read_sql("""
SELECT day_of_week, AVG(burnout_risk) AS burnout
FROM activities
GROUP BY day_of_week
ORDER BY burnout DESC
""", conn)

C:\Users\chira\AppData\Local\Temp\ipykernel_7152\2067471187.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("""

  day_of_week  burnout
0         mon      0.0
1         tue      0.0
2         wed      0.0
3         thu      0.0
4         fri      0.0
5         sat      0.0
6         sun      0.0

In [36]:
df_ml = pd.read_sql("SELECT * FROM activities", conn)
df_ml['completion_status'] = df_ml['completion_status'].map({'yes':1, 'no':0})
df_ml.head()

C:\Users\chira\AppData\Local\Temp\ipykernel_7152\2046312942.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ml = pd.read_sql("SELECT * FROM activities", conn)

,record_id,user_id,activity_date,day_of_week,activity_type,planned_time_hrs,actual_time_hrs,completion_status,interruption_count,energy_level,mood,invalid_time_flag,energy_missing_flag,duplicate_flag,efficiency,burnout_risk,high_interruption_flag
0,1,101,2025-11-01,mon,study,3.0,2.5,1,2,4,high,0,0,0,0.833333,0,0
1,2,101,2025-11-02,tue,study,2.0,3.0,1,5,3,neutral,0,0,0,1.500000,0,1
2,3,101,2025-11-03,wed,study,3.0,1.5,0,7,3,low,0,1,0,0.500000,0,1
3,4,101,2025-11-04,thu,work,4.0,4.5,1,1,5,high,0,0,0,1.125000,0,0
4,5,101,2025-11-05,fri,rest,1.0,0.5,0,3,2,low,0,0,0,0.500000,0,0